name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world
    - name: Log in docker hub
      run : docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASS}}
    - name: Push image to Dockerhub
      run : |
            docker tag hello-world ${{ secrets.DOCKER_USERNAME }}/app-flask
            docker push  ${{ secrets.DOCKER_USERNAME }}/app-flask
    - name: Deploy Docker Container to EC2
      uses: appleboy/ssh-action@master
      with:
       host:   # Replace with your EC2 instance IP or DNS
       username:  # The SSH username for your EC2 instance
       key:   # Your SSH private key (stored as a secret)
